In [1]:
import numpy as np
import pandas as pd
import matplotlib.pylab as plt 
from ChainModels import *  

PyPI recovery codes
a0c69f49009f92cb
98539460c37f1a0a
6c139bb14f27c702
e09003cb09437f3c
ab0b36e532ecc19a
c65a76b4c588eac3
8b436b3b12d82232
ca75a9b0e53a73b9

## Hnaya tatbqa t appliquihom directement 

Voici la matrix bash ankhdmo (jaya mn l R) : 

$$
\begin{array}{c|cccccccccc}
\text{} & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 \\
\hline
1981 & 5012 & 8269 & 10907 & 11805 & 13539 & 16181 & 18009 & 18608 & 18662 & 18834 \\
1982 & 106 & 4285 & 5396 & 10666 & 13782 & 15599 & 15496 & 16169 & 16704 & \text{NA} \\
1983 & 3410 & 8992 & 13873 & 16141 & 18735 & 22214 & 22863 & 23466 & \text{NA} & \text{NA} \\
1984 & 5655 & 11555 & 15766 & 21266 & 23425 & 26083 & 27067 & \text{NA} & \text{NA} & \text{NA} \\
1985 & 1092 & 9565 & 15836 & 22169 & 25955 & 26180 & \text{NA} & \text{NA} & \text{NA} & \text{NA} \\
1986 & 1513 & 6445 & 11702 & 12935 & 15852 & \text{NA} & \text{NA} & \text{NA} & \text{NA} & \text{NA} \\
1987 & 557 & 4020 & 10946 & 12314 & \text{NA} & \text{NA} & \text{NA} & \text{NA} & \text{NA} & \text{NA} \\
1988 & 1351 & 6947 & 13112 & \text{NA} & \text{NA} & \text{NA} & \text{NA} & \text{NA} & \text{NA} & \text{NA} \\
1989 & 3133 & 5395 & \text{NA} & \text{NA} & \text{NA} & \text{NA} & \text{NA} & \text{NA} & \text{NA} & \text{NA} \\
1990 & 2063 & \text{NA} & \text{NA} & \text{NA} & \text{NA} & \text{NA} & \text{NA} & \text{NA} & \text{NA} & \text{NA} \\
\end{array}
$$

Qui doit donner les résiltats suivantes pour chaine de mack/ladder : 

$$ 
\mathbf{f} = \begin{bmatrix}
2.999359 \\
1.623523 \\
1.270888 \\
1.171675 \\
1.113385 \\
1.041935 \\
1.033264 \\
1.016936 \\
1.009217 \\
1.000000
\end{bmatrix}  \quad\quad
\mathbf{v} = \begin{bmatrix}
166.983470 \\
33.294538 \\
26.295300 \\
7.824960 \\
10.928818 \\
6.389042 \\
1.159062 \\
2.807704 \\ 
1.159062 \\
NA
\end{bmatrix}
$$

Et triangle complet : 

$$ \begin{array}{c|cccccccccc}
\text{dev} & 1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 \\
\hline
1981 & 5012 & 8269.000 & 10907.000 & 11805.00 & 13539.00 & 16181.00 & 18009.00 & 18608.00 & 18662.00 & 18834.00 \\
1982 & 106 & 4285.000 & 5396.000 & 10666.00 & 13782.00 & 15599.00 & 15496.00 & 16169.00 & 16704.00 & 16857.95 \\
1983 & 3410 & 8992.000 & 13873.000 & 16141.00 & 18735.00 & 22214.00 & 22863.00 & 23466.00 & 23863.43 & 24083.37 \\
1984 & 5655 & 11555.000 & 15766.000 & 21266.00 & 23425.00 & 26083.00 & 27067.00 & 27967.34 & 28441.01 & 28703.14 \\
1985 & 1092 & 9565.000 & 15836.000 & 22169.00 & 25955.00 & 26180.00 & 27277.85 & 28185.21 & 28662.57 & 28926.74 \\
1986 & 1513 & 6445.000 & 11702.000 & 12935.00 & 15852.00 & 17649.38 & 18389.50 & 19001.20 & 19323.01 & 19501.10 \\
1987 & 557 & 4020.000 & 10946.000 & 12314.00 & 14428.00 & 16063.92 & 16737.55 & 17294.30 & 17587.21 & 17749.30 \\
1988 & 1351 & 6947.000 & 13112.000 & 16663.88 & 19524.65 & 21738.45 & 22650.05 & 23403.47 & 23799.84 & 24019.19 \\
1989 & 3133 & 5395.000 & 8758.905 & 11131.59 & 13042.60 & 14521.43 & 15130.38 & 15633.68 & 15898.45 & 16044.98 \\
1990 & 2063 & 6187.677 & 10045.834 & 12767.13 & 14958.92 & 16655.04 & 17353.46 & 17930.70 & 18234.38 & 18402.44 \\
\end{array}
$$

Et provisions : 

$$ 
\begin{array}{c|cccccc}
\text{ year} &\text{Latest} & \text{Dev.To.Date} & \text{Ultimate} & \text{IBNR} & \text{Mack.S.E} & \text{CV(IBNR)} \\
\hline
1981 & 18834 & 1.0000000 & 18834.00 & 0.0000 & 0.0000 & \text{NaN} \\
1982 & 16704 & 0.9908676 & 16857.95 & 153.9539 & 206.2201 & 1.3394921 \\
1983 & 23466 & 0.9743653 & 24083.37 & 617.3709 & 623.3767 & 1.0097279 \\
1984 & 27067 & 0.9429978 & 28703.14 & 1636.1422 & 747.1752 & 0.4566689 \\
1985 & 26180 & 0.9050451 & 28926.74 & 2746.7363 & 1469.4571 & 0.5349830 \\
1986 & 15852 & 0.8128771 & 19501.10 & 3649.1032 & 2001.8569 & 0.5485887 \\
1987 & 12314 & 0.6937737 & 17749.30 & 5435.3026 & 2209.2421 & 0.4064617 \\
1988 & 13112 & 0.5458968 & 24019.19 & 10907.1925 & 5357.8693 & 0.4912235 \\
1989 & 5395 & 0.3362422 & 16044.98 & 10649.9841 & 6333.1659 & 0.5946643 \\
1990 & 2063 & 0.1121047 & 18402.44 & 16339.4425 & 24566.2879 & 1.5034961 \\
\end{array}
$$

In [2]:
C = np.array([
    [5012, 8269, 10907, 11805, 13539, 16181, 18009, 18608, 18662, 18834],
    [106, 4285, 5396, 10666, 13782, 15599, 15496, 16169, 16704, np.nan],
    [3410, 8992, 13873, 16141, 18735, 22214, 22863, 23466, np.nan, np.nan],
    [5655, 11555, 15766, 21266, 23425, 26083, 27067, np.nan, np.nan, np.nan],
    [1092, 9565, 15836, 22169, 25955, 26180, np.nan, np.nan, np.nan, np.nan],
    [1513, 6445, 11702, 12935, 15852, np.nan, np.nan, np.nan, np.nan, np.nan],
    [557, 4020, 10946, 12314, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan],
    [1351, 6947, 13112, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan],
    [3133, 5395, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan],
    [2063, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan]
])

years = [1981,1982,1983,1984,1985,1986,1987,1988,1989,1990]

triangle = Triangle(years=years,data=C,isCumul=True)
print(triangle)

Increment = 
           0       1       2       3       4       5       6      7      8   
1981  5012.0  3257.0  2638.0   898.0  1734.0  2642.0  1828.0  599.0   54.0  \
1982   106.0  4179.0  1111.0  5270.0  3116.0  1817.0  -103.0  673.0  535.0   
1983  3410.0  5582.0  4881.0  2268.0  2594.0  3479.0   649.0  603.0    NaN   
1984  5655.0  5900.0  4211.0  5500.0  2159.0  2658.0   984.0    NaN    NaN   
1985  1092.0  8473.0  6271.0  6333.0  3786.0   225.0     NaN    NaN    NaN   
1986  1513.0  4932.0  5257.0  1233.0  2917.0     NaN     NaN    NaN    NaN   
1987   557.0  3463.0  6926.0  1368.0     NaN     NaN     NaN    NaN    NaN   
1988  1351.0  5596.0  6165.0     NaN     NaN     NaN     NaN    NaN    NaN   
1989  3133.0  2262.0     NaN     NaN     NaN     NaN     NaN    NaN    NaN   
1990  2063.0     NaN     NaN     NaN     NaN     NaN     NaN    NaN    NaN   

          9  
1981  172.0  
1982    NaN  
1983    NaN  
1984    NaN  
1985    NaN  
1986    NaN  
1987    NaN  
1988    NaN  
19

In [3]:
model = ChainLadderBoot(1_000)

In [4]:
model.fit(triangle)

In [5]:
model.DevFactors

array([3.00889019, 1.62812826, 1.27292181, 1.17224733, 1.11352247,
       1.04214661, 1.03291707, 1.01720877, 1.00938507])

In [7]:
model.glmchain.Residuals

array([[ 7.80257276e+01, -1.83468317e+01, -2.57803293e+01,
        -4.41984276e+01, -1.32885882e+01,  2.68812160e+01,
         5.14647344e+01,  4.18283315e-01, -1.80048391e+01,
        -6.69662646e-14],
       [-5.07195601e+01,  8.05330034e+00, -5.03838374e+01,
         6.87493338e+01,  3.05681112e+01,  8.25436653e+00,
        -3.62978765e+01,  7.75139505e+00,  1.90308461e+01,
                    nan],
       [ 1.68929058e+01,  3.09574754e+00, -2.92563514e+00,
        -2.67883419e+01, -6.33300335e+00,  3.30373548e+01,
        -1.08353936e+01, -6.85510337e+00,             nan,
                    nan],
       [ 5.31070752e+01, -8.22056320e+00, -2.87879289e+01,
         2.38188273e+01, -2.66287007e+01,  3.00136953e-01,
        -3.94576453e+00,             nan,             nan,
                    nan],
       [-4.66845411e+01,  3.05388580e+01,  3.27556866e+00,
         3.88442726e+01,  7.17508673e+00, -5.84358353e+01,
                    nan,             nan,             nan,
           

In [8]:
model.SimProvisionsTotal

array([46536.45632548, 53602.1064488 , 51399.77250524, 48219.19811271,
       47772.98386617, 41823.15443428, 57887.12014632, 51933.40531697,
       46545.30138781, 49999.08863036, 53100.35618835, 38894.63201259,
       41211.1117633 , 49946.86341553, 61179.31562074, 40858.12617862,
       49369.10132313, 47937.79126684, 49470.27750318, 54249.52961525,
       46157.60648511, 60191.72519825, 52028.28665741, 60528.53643705,
       59963.70711287, 62461.33171326, 52457.90728561, 47371.19820443,
       50627.99586366, 55917.70569233, 49748.32149733, 54346.43408495,
       52192.23655491, 47737.9457896 , 47511.73191772, 55069.04284084,
       52715.44018288, 56178.0347213 , 60443.34572125, 53224.85188411,
       45998.31341064, 49742.99514356, 50338.13008896, 53027.13894652,
       53625.44572536, 48781.34284563, 62114.31287873, 48116.52372473,
       42708.26661769, 61222.83707774, 62397.37093921, 51892.45010851,
       51193.48180811, 59377.83912564, 53703.42442385, 48015.05974359,
      